export const REDIS_SOCKET_EVENT_EMIT = 'REDIS_SOCKET_EVENT_EMIT'
export const REDIS_SOCKET_EVENT_EMIT_ROOM = 'REDIS_SOCKET_EVENT_EMIT_ROOM'
export const REDIS_SOCKET_EVENT_EMIT_USER = 'REDIS_SOCKET_EVENT_USER'
